version: '3'
name: dick_steinkamp_us_dev
services:
  web:
    build:
      context: .
      target: dev
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
volumes:
  app_node_modules:
