title: Timeline
date: 1964-01-01
thumbnail: /images/timeline/30_ford_modal_a_coupe.jpg
excerpt: I've bought, fixed up, and sold over 50 cars, motorcycles, boats, and tractors. Check out this list of all of the projects.
slug: /timeline
